### ISSUE TITLE
학습데이터 관련

### ISSUE THREAD

**Issue by SunKyungCho** [muik/transliteration#2]
영어 독음 번역 관련해서 알아보던중에 발견해서 소스를 분석해 봤는데요.
소스에는 학습데이터를 읽어올때 .en, .fr 파일만 읽어오고
/source 디렉토리 내부의 데이터는 읽어오는 부분을 찾을 수가 없는데
어떻게 데이터가 반영되는 건지 알려주실 수 있나요?

**Comment by muik** [comment]
source는 직접 읽지는 않고 학습파일을 만드는데 사용했는데요. 참고하시라고 올려놓은 것 입니다~!
